# Generated by Django 5.2.4 on 2025-08-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
