# Generated by Django 5.2.4 on 2025-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
